name: Java CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 22
      uses: actions/setup-java@v2
      with:
        java-version: '22'
        distribution: 'temurin'
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Run Tests
      run: mvn -B test --file pom.xml

    - name: Failure send
      if: failure()
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.BOT_ID }}
        CHAT_ID: ${{ secrets.CHAT_ID }}
      run: |
          MESSAGE="Якорь мне в бухту! Мы идем на дно!"
          # FAILED_TESTS=$(grep '<<< FAILURE!' target/surefire-reports/org.example.NumbersProcessorTest.txt)
          curl -s -X POST https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage -d "chat_id=${CHAT_ID}&text=${MESSAGE} ${FAILED_TESTS}"
    - name: Success send
      if: success()
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.BOT_ID }}
        CHAT_ID: ${{ secrets.CHAT_ID }}
      run: |
        MESSAGE="Тысяча вонючих китов и ржавых медуз! Наша шхуна все еще на плаву!"
        curl -s -X POST https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage -d "chat_id=${CHAT_ID}&text=${MESSAGE}"
    
