name: Java CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Download JUnit 5
      run: |
        mkdir -p junit5
        cd junit5
        wget https://repo1.maven.org/maven2/org/junit/platform/junit-platform-console-standalone/1.8.2/junit-platform-console-standalone-1.8.2.jar

    - name: List directory contents
      run: ls -R

    - name: Compile and run tests
      run: |
        javac -cp .:junit5/junit-platform-console-standalone-1.8.2.jar src/test/java/org/example/*.java
        java -jar junit5/junit-platform-console-standalone-1.8.2.jar -cp src/test/java/org/example --select-class org.example.functest
 
