name: Java CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 22
      uses: actions/setup-java@v2
      with:
        java-version: '22'
        distribution: 'temurin'
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Run Tests
      run: mvn -B test --file pom.xml
    - name: Send Telegram notification
      if: always()
      run: |
        TEST_RESULT=${{ steps.test.outcome }}
        TELEGRAM_MESSAGE=""
        if [ "$TEST_RESULT" == "success" ]; then
          TELEGRAM_MESSAGE="Тысяча вонючих китов и ржавых медуз! Наша шхуна все еще на плаву!."
        else
          TELEGRAM_MESSAGE="Якорь мне вв бухту! Мы идем на дно!."
          mvn test | grep -A 5 "Tests run" >> test_report.txt
          TEST_REPORT=$(cat test_report.txt)
          TELEGRAM_MESSAGE="$TELEGRAM_MESSAGE\n\n$TEST_REPORT"
        fi
        curl -s -X POST https://api.telegram.org/bot${{ secrets.BOT_ID }}/sendMessage \
          -d chat_id=${{ secrets.CHAT_ID }} \
          -d text="$TELEGRAM_MESSAGE"
